ALTER TABLE dbo.TCF028_PRODUCT_AGRUP  
ADD CD_PROVEEDOR char(6) null
GO

ALTER TABLE dbo.TCF028_PRODUCT_AGRUP  
ADD ST_HABILITADO char(1) null
GO

update TCF028_PRODUCT_AGRUP 
SET TCF028_PRODUCT_AGRUP.CD_PROVEEDOR = (SELECT b.CD_PROVEEDOR FROM TCF005_PRODUCTO b WHERE b.CD_PRODUCTO = TCF028_PRODUCT_AGRUP.CD_PRODUCTO), 
    ST_HABILITADO = (SELECT b.ST_HABILITADO FROM TCF005_PRODUCTO b WHERE b.CD_PRODUCTO = TCF028_PRODUCT_AGRUP.CD_PRODUCTO)
GO
