UPDATE TCF005_PRODUCTO
SET NB_ATRIBUTOADIC1 = 'N'
GO

UPDATE TCF005_PRODUCTO
SET NB_ATRIBUTOADIC1 = 'S'
WHERE CD_PRODUCTO IN (SELECT AGR.CD_PRODUCTO FROM TCF028_PRODUCT_AGRUP AGR)
GO	 

UPDATE TCF005_PRODUCTO
SET NB_ATRIBUTOADIC1 = 'S'
WHERE CD_PRODUCTO IN (SELECT AGR.CD_PRODUCTO_ORIG FROM TCF028_PRODUCT_AGRUP AGR)
GO
