INSERT INTO dbo.TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF) 
VALUES('GRUPRO','NO_CON','No Conciliados','No Conciliados',NULL,NULL,NULL,'S','2016-06-15 11:12:00.000','admin',NULL,NULL)
