package com.gefa.model;
// Generated 20/08/2014 15:01:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
/**
 * GefaModificaciones generated by hbm2java
 */
 @Entity
public class GefaModificaciones implements java.io.Serializable {

	private int n;
	private String codInterno;
	private String codPpm;
	private String codAdicional;
	private String nombrePpm;
	private String factoria;
	private String tecnologia;
	private String subproyecto;
	private String nombreDelComponente;
	private String entregaAsociada;
	private String modificacionEnVuelo;
	private String modificacionYaRealizadaPorDyD;
	private String estado;
	private String descripcion;
	private Date fechaEnvio;
	private Date fprevistaFinalizacion;
	private Date fechaRenegociada;
	private Date fechaCierre;
	private String comentariosModificacion;
	private String tipologia;
	private String difIni;
	private Double costeIni;
	private Double horasIni;
	private String difFact;
	private Double costeFact;
	private Double horasFact;
	private String divisa;
	private String comentariosTipificacionFactoria;
	private String comentariosTipificacionProyecto;
	private String estadoTipificacion;
	private String factSn;
	private String mesFact;
	private String anioFact;
	private String codPresupuestario;
	private String sociedadDelPep;
	private String responsableEjecucionPep;
	private String prioridadUsuario;
	private String usuarioPeticionario;
	private String origen;
	private String responsableResolucion;
	private Integer numErrorAsociado;
	private String tieneModEnVueloAsociadas;
	private String ndeModAsociada;
	private String rutaDeRed;
	private Integer ndePeticionSoloHost;
	private Date fechaLibFact;
	private Date fechaAlta;
	private Date fechaMod;
	private Date fechaBaja;
	private String nombreArchivoCarga;

	public GefaModificaciones() {
	}

	public GefaModificaciones(int n) {
		this.n = n;
	}

	public GefaModificaciones(int n, String codInterno, String codPpm,
			String codAdicional, String nombrePpm, String factoria,
			String tecnologia, String subproyecto, String nombreDelComponente,
			String entregaAsociada, String modificacionEnVuelo,
			String modificacionYaRealizadaPorDyD, String estado,
			String descripcion, Date fechaEnvio, Date fprevistaFinalizacion,
			Date fechaRenegociada, Date fechaCierre,
			String comentariosModificacion, String tipologia, String difIni,
			Double costeIni, Double horasIni, String difFact, Double costeFact,
			Double horasFact, String divisa,
			String comentariosTipificacionFactoria,
			String comentariosTipificacionProyecto, String estadoTipificacion,
			String factSn, String mesFact, String anioFact,
			String codPresupuestario, String sociedadDelPep,
			String responsableEjecucionPep, String prioridadUsuario,
			String usuarioPeticionario, String origen,
			String responsableResolucion, Integer numErrorAsociado,
			String tieneModEnVueloAsociadas, String ndeModAsociada,
			String rutaDeRed, String ndePeticionSoloHost, Date fechaLibFact,
			Date fechaAlta, Date fechaMod, Date fechaBaja,
			String nombreArchivoCarga) {
		this.n = n;
		this.codInterno = codInterno;
		this.codPpm = codPpm;
		this.codAdicional = codAdicional;
		this.nombrePpm = nombrePpm;
		this.factoria = factoria;
		this.tecnologia = tecnologia;
		this.subproyecto = subproyecto;
		this.nombreDelComponente = nombreDelComponente;
		this.entregaAsociada = entregaAsociada;
		this.modificacionEnVuelo = modificacionEnVuelo;
		this.modificacionYaRealizadaPorDyD = modificacionYaRealizadaPorDyD;
		this.estado = estado;
		this.descripcion = descripcion;
		this.fechaEnvio = fechaEnvio;
		this.fprevistaFinalizacion = fprevistaFinalizacion;
		this.fechaRenegociada = fechaRenegociada;
		this.fechaCierre = fechaCierre;
		this.comentariosModificacion = comentariosModificacion;
		this.tipologia = tipologia;
		this.difIni = difIni;
		this.costeIni = costeIni;
		this.horasIni = horasIni;
		this.difFact = difFact;
		this.costeFact = costeFact;
		this.horasFact = horasFact;
		this.divisa = divisa;
		this.comentariosTipificacionFactoria = comentariosTipificacionFactoria;
		this.comentariosTipificacionProyecto = comentariosTipificacionProyecto;
		this.estadoTipificacion = estadoTipificacion;
		this.factSn = factSn;
		this.mesFact = mesFact;
		this.anioFact = anioFact;
		this.codPresupuestario = codPresupuestario;
		this.sociedadDelPep = sociedadDelPep;
		this.responsableEjecucionPep = responsableEjecucionPep;
		this.prioridadUsuario = prioridadUsuario;
		this.usuarioPeticionario = usuarioPeticionario;
		this.origen = origen;
		this.responsableResolucion = responsableResolucion;
		this.numErrorAsociado = numErrorAsociado;
		this.tieneModEnVueloAsociadas = tieneModEnVueloAsociadas;
		this.ndeModAsociada = ndeModAsociada;
		this.rutaDeRed = rutaDeRed;
		if( ndePeticionSoloHost == null
		||  ndePeticionSoloHost.trim().isEmpty())
			this.ndePeticionSoloHost = null;
		else
			this.ndePeticionSoloHost =  Integer.valueOf( ndePeticionSoloHost);
		this.fechaLibFact = fechaLibFact;
		this.fechaLibFact = fechaLibFact;
		this.fechaAlta = fechaAlta;
		this.fechaMod = fechaMod;
		this.fechaBaja = fechaBaja;
		this.nombreArchivoCarga = nombreArchivoCarga;
	}

	public int getN() {
		return this.n;
	}

	public void setN(int n) {
		this.n = n;
	}

	public String getCodInterno() {
		return this.codInterno;
	}

	public void setCodInterno(String codInterno) {
		this.codInterno = codInterno;
	}

	public String getCodPpm() {
		return this.codPpm;
	}

	public void setCodPpm(String codPpm) {
		this.codPpm = codPpm;
	}

	public String getCodAdicional() {
		return this.codAdicional;
	}

	public void setCodAdicional(String codAdicional) {
		this.codAdicional = codAdicional;
	}

	public String getNombrePpm() {
		return this.nombrePpm;
	}

	public void setNombrePpm(String nombrePpm) {
		this.nombrePpm = nombrePpm;
	}

	public String getFactoria() {
		return this.factoria;
	}

	public void setFactoria(String factoria) {
		this.factoria = factoria;
	}

	public String getTecnologia() {
		return this.tecnologia;
	}

	public void setTecnologia(String tecnologia) {
		this.tecnologia = tecnologia;
	}

	public String getSubproyecto() {
		return this.subproyecto;
	}

	public void setSubproyecto(String subproyecto) {
		this.subproyecto = subproyecto;
	}

	public String getNombreDelComponente() {
		return this.nombreDelComponente;
	}

	public void setNombreDelComponente(String nombreDelComponente) {
		this.nombreDelComponente = nombreDelComponente;
	}

	public String getEntregaAsociada() {
		return this.entregaAsociada;
	}

	public void setEntregaAsociada(String entregaAsociada) {
		this.entregaAsociada = entregaAsociada;
	}

	public String getModificacionEnVuelo() {
		return this.modificacionEnVuelo;
	}

	public void setModificacionEnVuelo(String modificacionEnVuelo) {
		this.modificacionEnVuelo = modificacionEnVuelo;
	}

	public String getModificacionYaRealizadaPorDyD() {
		return this.modificacionYaRealizadaPorDyD;
	}

	public void setModificacionYaRealizadaPorDyD(
			String modificacionYaRealizadaPorDyD) {
		this.modificacionYaRealizadaPorDyD = modificacionYaRealizadaPorDyD;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public Date getFprevistaFinalizacion() {
		return this.fprevistaFinalizacion;
	}

	public void setFprevistaFinalizacion(Date fprevistaFinalizacion) {
		this.fprevistaFinalizacion = fprevistaFinalizacion;
	}

	public Date getFechaRenegociada() {
		return this.fechaRenegociada;
	}

	public void setFechaRenegociada(Date fechaRenegociada) {
		this.fechaRenegociada = fechaRenegociada;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public String getComentariosModificacion() {
		return this.comentariosModificacion;
	}

	public void setComentariosModificacion(String comentariosModificacion) {
		this.comentariosModificacion = comentariosModificacion;
	}

	public String getTipologia() {
		return this.tipologia;
	}

	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}

	public String getDifIni() {
		return this.difIni;
	}

	public void setDifIni(String difIni) {
		this.difIni = difIni;
	}

	public Double getCosteIni() {
		return this.costeIni;
	}

	public void setCosteIni(Double costeIni) {
		this.costeIni = costeIni;
	}

	public Double getHorasIni() {
		return this.horasIni;
	}

	public void setHorasIni(Double horasIni) {
		this.horasIni = horasIni;
	}

	public String getDifFact() {
		return this.difFact;
	}

	public void setDifFact(String difFact) {
		this.difFact = difFact;
	}

	public Double getCosteFact() {
		return this.costeFact;
	}

	public void setCosteFact(Double costeFact) {
		this.costeFact = costeFact;
	}

	public Double getHorasFact() {
		return this.horasFact;
	}

	public void setHorasFact(Double horasFact) {
		this.horasFact = horasFact;
	}

	public String getDivisa() {
		return this.divisa;
	}

	public void setDivisa(String divisa) {
		this.divisa = divisa;
	}

	public String getComentariosTipificacionFactoria() {
		return this.comentariosTipificacionFactoria;
	}

	public void setComentariosTipificacionFactoria(
			String comentariosTipificacionFactoria) {
		this.comentariosTipificacionFactoria = comentariosTipificacionFactoria;
	}

	public String getComentariosTipificacionProyecto() {
		return this.comentariosTipificacionProyecto;
	}

	public void setComentariosTipificacionProyecto(
			String comentariosTipificacionProyecto) {
		this.comentariosTipificacionProyecto = comentariosTipificacionProyecto;
	}

	public String getEstadoTipificacion() {
		return this.estadoTipificacion;
	}

	public void setEstadoTipificacion(String estadoTipificacion) {
		this.estadoTipificacion = estadoTipificacion;
	}

	public String getFactSn() {
		return this.factSn;
	}

	public void setFactSn(String factSn) {
		this.factSn = factSn;
	}

	public String getMesFact() {
		return this.mesFact;
	}

	public void setMesFact(String mesFact) {
		this.mesFact = mesFact;
	}

	public String getAnioFact() {
		return this.anioFact;
	}

	public void setAnioFact(String anioFact) {
		this.anioFact = anioFact;
	}

	public String getCodPresupuestario() {
		return this.codPresupuestario;
	}

	public void setCodPresupuestario(String codPresupuestario) {
		this.codPresupuestario = codPresupuestario;
	}

	public String getSociedadDelPep() {
		return this.sociedadDelPep;
	}

	public void setSociedadDelPep(String sociedadDelPep) {
		this.sociedadDelPep = sociedadDelPep;
	}

	public String getResponsableEjecucionPep() {
		return this.responsableEjecucionPep;
	}

	public void setResponsableEjecucionPep(String responsableEjecucionPep) {
		this.responsableEjecucionPep = responsableEjecucionPep;
	}

	public String getPrioridadUsuario() {
		return this.prioridadUsuario;
	}

	public void setPrioridadUsuario(String prioridadUsuario) {
		this.prioridadUsuario = prioridadUsuario;
	}

	public String getUsuarioPeticionario() {
		return this.usuarioPeticionario;
	}

	public void setUsuarioPeticionario(String usuarioPeticionario) {
		this.usuarioPeticionario = usuarioPeticionario;
	}

	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getResponsableResolucion() {
		return this.responsableResolucion;
	}

	public void setResponsableResolucion(String responsableResolucion) {
		this.responsableResolucion = responsableResolucion;
	}

	public Integer getNumErrorAsociado() {
		return this.numErrorAsociado;
	}

	public void setNumErrorAsociado(Integer numErrorAsociado) {
		this.numErrorAsociado = numErrorAsociado;
	}

	public String getTieneModEnVueloAsociadas() {
		return this.tieneModEnVueloAsociadas;
	}

	public void setTieneModEnVueloAsociadas(String tieneModEnVueloAsociadas) {
		this.tieneModEnVueloAsociadas = tieneModEnVueloAsociadas;
	}

	public String getNdeModAsociada() {
		return this.ndeModAsociada;
	}

	public void setNdeModAsociada(String ndeModAsociada) {
		this.ndeModAsociada = ndeModAsociada;
	}

	public String getRutaDeRed() {
		return this.rutaDeRed;
	}

	public void setRutaDeRed(String rutaDeRed) {
		this.rutaDeRed = rutaDeRed;
	}

	public Integer getNdePeticionSoloHost() {
		return this.ndePeticionSoloHost;
	}

	public void setNdePeticionSoloHost(Integer ndePeticionSoloHost) {
		this.ndePeticionSoloHost = ndePeticionSoloHost;
	}

	public Date getFechaLibFact() {
		return this.fechaLibFact;
	}

	public void setFechaLibFact(Date fechaLibFact) {
		this.fechaLibFact = fechaLibFact;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getNombreArchivoCarga() {
		return this.nombreArchivoCarga;
	}

	public void setNombreArchivoCarga(String nombreArchivoCarga) {
		this.nombreArchivoCarga = nombreArchivoCarga;
	}

}
