package com.gefa.model;
// Generated 20/08/2014 14:52:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GefaAlta generated by hbm2java
 */
public class GefaAlta implements java.io.Serializable {

	private Integer id;
	private String tipologDificultadDistintos;
	private String codInterno;
	private String codPpm;
	private String codAdicional;
	private String nombreDeProyecto;
	private String entrega;
	private String codFactoria;
	private String factoria;
	private String tecnologia;
	private String subproyecto;
	private String nombreComponente;
	private String programaNuevoModificado;
	private String estado;
	private Date fechaRealCfgFactDisenio;
	private Date fechaPrevistaFactCgfsoftware;
	private Date fechaNegociadaFactCgfSoftware;
	private Date fechaRealFactCgfsoftware;
	private String tipologiaInicial;
	private String difIni;
	private Double costeIni;
	private Double horasIni;
	private String tipologiaFactorias;
	private String difFact;
	private Double costeFact;
	private Double horasFact;
	private String divisa;
	private String comentariosTipoficacionFactoria;
	private String comentariosTipoficacionProyecto;
	private String estadoTipificacion;
	private String factSn;
	private String mesFact;
	private String anioFact;
	private String observaciones;
	private String metCal;
	private String codPresupuestario;
	private String responsableEjecucionPep;
	private String sociedadDelPep;
	private Date fechaLibFact;
	private Integer pmredmine;
	private String f013;
	private Date fechaAlta;
	private Date fechaMod;
	private Date fechaBaja;
	private String nombreArchivoCarga;

	public GefaAlta() {
	}

	public GefaAlta(Date fechaRealCfgFactDisenio) {
		this.fechaRealCfgFactDisenio = fechaRealCfgFactDisenio;
	}

	public GefaAlta(String tipologDificultadDistintos, String codInterno,
			String codPpm, String codAdicional, String nombreDeProyecto,
			String entrega, String codFactoria, String factoria,
			String tecnologia, String subproyecto, String nombreComponente,
			String programaNuevoModificado, String estado,
			Date fechaRealCfgFactDisenio, Date fechaPrevistaFactCgfsoftware,
			Date fechaNegociadaFactCgfSoftware, Date fechaRealFactCgfsoftware,
			String tipologiaInicial, String difIni, Double costeIni,
			Double horasIni, String tipologiaFactorias, String difFact,
			Double costeFact, Double horasFact, String divisa,
			String comentariosTipoficacionFactoria,
			String comentariosTipoficacionProyecto, String estadoTipificacion,
			String factSn, String mesFact, String anioFact,
			String observaciones, String metCal, String codPresupuestario,
			String responsableEjecucionPep, String sociedadDelPep,
			Date fechaLibFact, Integer pmredmine, String f013, Date fechaAlta,
			Date fechaMod, Date fechaBaja, String nombreArchivoCarga) {
		this.tipologDificultadDistintos = tipologDificultadDistintos;
		this.codInterno = codInterno;
		this.codPpm = codPpm;
		this.codAdicional = codAdicional;
		this.nombreDeProyecto = nombreDeProyecto;
		this.entrega = entrega;
		this.codFactoria = codFactoria;
		this.factoria = factoria;
		this.tecnologia = tecnologia;
		this.subproyecto = subproyecto;
		this.nombreComponente = nombreComponente;
		this.programaNuevoModificado = programaNuevoModificado;
		this.estado = estado;
		this.fechaRealCfgFactDisenio = fechaRealCfgFactDisenio;
		this.fechaPrevistaFactCgfsoftware = fechaPrevistaFactCgfsoftware;
		this.fechaNegociadaFactCgfSoftware = fechaNegociadaFactCgfSoftware;
		this.fechaRealFactCgfsoftware = fechaRealFactCgfsoftware;
		this.tipologiaInicial = tipologiaInicial;
		this.difIni = difIni;
		this.costeIni = costeIni;
		this.horasIni = horasIni;
		this.tipologiaFactorias = tipologiaFactorias;
		this.difFact = difFact;
		this.costeFact = costeFact;
		this.horasFact = horasFact;
		this.divisa = divisa;
		this.comentariosTipoficacionFactoria = comentariosTipoficacionFactoria;
		this.comentariosTipoficacionProyecto = comentariosTipoficacionProyecto;
		this.estadoTipificacion = estadoTipificacion;
		this.factSn = factSn;
		this.mesFact = mesFact;
		this.anioFact = anioFact;
		this.observaciones = observaciones;
		this.metCal = metCal;
		this.codPresupuestario = codPresupuestario;
		this.responsableEjecucionPep = responsableEjecucionPep;
		this.sociedadDelPep = sociedadDelPep;
		this.fechaLibFact = fechaLibFact;
		this.pmredmine = pmredmine;
		this.f013 = f013;
		this.fechaAlta = fechaAlta;
		this.fechaMod = fechaMod;
		this.fechaBaja = fechaBaja;
		this.nombreArchivoCarga = nombreArchivoCarga;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTipologDificultadDistintos() {
		return this.tipologDificultadDistintos;
	}

	public void setTipologDificultadDistintos(String tipologDificultadDistintos) {
		this.tipologDificultadDistintos = tipologDificultadDistintos;
	}

	public String getCodInterno() {
		return this.codInterno;
	}

	public void setCodInterno(String codInterno) {
		this.codInterno = codInterno;
	}

	public String getCodPpm() {
		return this.codPpm;
	}

	public void setCodPpm(String codPpm) {
		this.codPpm = codPpm;
	}

	public String getCodAdicional() {
		return this.codAdicional;
	}

	public void setCodAdicional(String codAdicional) {
		this.codAdicional = codAdicional;
	}

	public String getNombreDeProyecto() {
		return this.nombreDeProyecto;
	}

	public void setNombreDeProyecto(String nombreDeProyecto) {
		this.nombreDeProyecto = nombreDeProyecto;
	}

	public String getEntrega() {
		return this.entrega;
	}

	public void setEntrega(String entrega) {
		this.entrega = entrega;
	}

	public String getCodFactoria() {
		return this.codFactoria;
	}

	public void setCodFactoria(String codFactoria) {
		this.codFactoria = codFactoria;
	}

	public String getFactoria() {
		return this.factoria;
	}

	public void setFactoria(String factoria) {
		this.factoria = factoria;
	}

	public String getTecnologia() {
		return this.tecnologia;
	}

	public void setTecnologia(String tecnologia) {
		this.tecnologia = tecnologia;
	}

	public String getSubproyecto() {
		return this.subproyecto;
	}

	public void setSubproyecto(String subproyecto) {
		this.subproyecto = subproyecto;
	}

	public String getNombreComponente() {
		return this.nombreComponente;
	}

	public void setNombreComponente(String nombreComponente) {
		this.nombreComponente = nombreComponente;
	}

	public String getProgramaNuevoModificado() {
		return this.programaNuevoModificado;
	}

	public void setProgramaNuevoModificado(String programaNuevoModificado) {
		this.programaNuevoModificado = programaNuevoModificado;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRealCfgFactDisenio() {
		return this.fechaRealCfgFactDisenio;
	}

	public void setFechaRealCfgFactDisenio(Date fechaRealCfgFactDisenio) {
		this.fechaRealCfgFactDisenio = fechaRealCfgFactDisenio;
	}

	public Date getFechaPrevistaFactCgfsoftware() {
		return this.fechaPrevistaFactCgfsoftware;
	}

	public void setFechaPrevistaFactCgfsoftware(
			Date fechaPrevistaFactCgfsoftware) {
		this.fechaPrevistaFactCgfsoftware = fechaPrevistaFactCgfsoftware;
	}

	public Date getFechaNegociadaFactCgfSoftware() {
		return this.fechaNegociadaFactCgfSoftware;
	}

	public void setFechaNegociadaFactCgfSoftware(
			Date fechaNegociadaFactCgfSoftware) {
		this.fechaNegociadaFactCgfSoftware = fechaNegociadaFactCgfSoftware;
	}

	public Date getFechaRealFactCgfsoftware() {
		return this.fechaRealFactCgfsoftware;
	}

	public void setFechaRealFactCgfsoftware(Date fechaRealFactCgfsoftware) {
		this.fechaRealFactCgfsoftware = fechaRealFactCgfsoftware;
	}

	public String getTipologiaInicial() {
		return this.tipologiaInicial;
	}

	public void setTipologiaInicial(String tipologiaInicial) {
		this.tipologiaInicial = tipologiaInicial;
	}

	public String getDifIni() {
		return this.difIni;
	}

	public void setDifIni(String difIni) {
		this.difIni = difIni;
	}

	public Double getCosteIni() {
		return this.costeIni;
	}

	public void setCosteIni(Double costeIni) {
		this.costeIni = costeIni;
	}

	public Double getHorasIni() {
		return this.horasIni;
	}

	public void setHorasIni(Double horasIni) {
		this.horasIni = horasIni;
	}

	public String getTipologiaFactorias() {
		return this.tipologiaFactorias;
	}

	public void setTipologiaFactorias(String tipologiaFactorias) {
		this.tipologiaFactorias = tipologiaFactorias;
	}

	public String getDifFact() {
		return this.difFact;
	}

	public void setDifFact(String difFact) {
		this.difFact = difFact;
	}

	public Double getCosteFact() {
		return this.costeFact;
	}

	public void setCosteFact(Double costeFact) {
		this.costeFact = costeFact;
	}

	public Double getHorasFact() {
		return this.horasFact;
	}

	public void setHorasFact(Double horasFact) {
		this.horasFact = horasFact;
	}

	public String getDivisa() {
		return this.divisa;
	}

	public void setDivisa(String divisa) {
		this.divisa = divisa;
	}

	public String getComentariosTipoficacionFactoria() {
		return this.comentariosTipoficacionFactoria;
	}

	public void setComentariosTipoficacionFactoria(
			String comentariosTipoficacionFactoria) {
		this.comentariosTipoficacionFactoria = comentariosTipoficacionFactoria;
	}

	public String getComentariosTipoficacionProyecto() {
		return this.comentariosTipoficacionProyecto;
	}

	public void setComentariosTipoficacionProyecto(
			String comentariosTipoficacionProyecto) {
		this.comentariosTipoficacionProyecto = comentariosTipoficacionProyecto;
	}

	public String getEstadoTipificacion() {
		return this.estadoTipificacion;
	}

	public void setEstadoTipificacion(String estadoTipificacion) {
		this.estadoTipificacion = estadoTipificacion;
	}

	public String getFactSn() {
		return this.factSn;
	}

	public void setFactSn(String factSn) {
		this.factSn = factSn;
	}

	public String getMesFact() {
		return this.mesFact;
	}

	public void setMesFact(String mesFact) {
		this.mesFact = mesFact;
	}

	public String getAnioFact() {
		return this.anioFact;
	}

	public void setAnioFact(String anioFact) {
		this.anioFact = anioFact;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getMetCal() {
		return this.metCal;
	}

	public void setMetCal(String metCal) {
		this.metCal = metCal;
	}

	public String getCodPresupuestario() {
		return this.codPresupuestario;
	}

	public void setCodPresupuestario(String codPresupuestario) {
		this.codPresupuestario = codPresupuestario;
	}

	public String getResponsableEjecucionPep() {
		return this.responsableEjecucionPep;
	}

	public void setResponsableEjecucionPep(String responsableEjecucionPep) {
		this.responsableEjecucionPep = responsableEjecucionPep;
	}

	public String getSociedadDelPep() {
		return this.sociedadDelPep;
	}

	public void setSociedadDelPep(String sociedadDelPep) {
		this.sociedadDelPep = sociedadDelPep;
	}

	public Date getFechaLibFact() {
		return this.fechaLibFact;
	}

	public void setFechaLibFact(Date fechaLibFact) {
		this.fechaLibFact = fechaLibFact;
	}

	public Integer getPmredmine() {
		return this.pmredmine;
	}

	public void setPmredmine(Integer pmredmine) {
		this.pmredmine = pmredmine;
	}

	public String getF013() {
		return this.f013;
	}

	public void setF013(String f013) {
		this.f013 = f013;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getNombreArchivoCarga() {
		return this.nombreArchivoCarga;
	}

	public void setNombreArchivoCarga(String nombreArchivoCarga) {
		this.nombreArchivoCarga = nombreArchivoCarga;
	}

}
