USE CFACSERV
GO

ALTER TABLE TCF001_GENERAL
MODIFY CD_CODTABLA VARCHAR(12) NOT NULL
GO

INSERT INTO dbo.TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF) 
VALUES('GRUPRO','CON_MONTO_TO','CONC_MONTO_TOTAL','Monto_Total',NULL,NULL,NULL,'S','2016-12-05 14:03:09.253','XA01073 ',NULL,NULL)
GO
