--Elimina los accesos restringidos de configurador
DELETE FROM dbo.TCF018_ACCESOS_POR_PERFILES WHERE ID_ACCESO='ABMC_USU' AND ID_PERFIL=6
go
DELETE FROM dbo.TCF018_ACCESOS_POR_PERFILES WHERE ID_ACCESO='ALTA_USU' AND ID_PERFIL=6
go
DELETE FROM dbo.TCF018_ACCESOS_POR_PERFILES WHERE ID_ACCESO='ANULAR_CONCIL' AND ID_PERFIL=7
go

--Agrega el acceso a las pantall de consulta de conciliaciones
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('BUSQUEDA_CONCIL',2,getdate())
go

INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ANULAR_CONCIL',4,getdate())
go

--Permisos de ANULAR LOTE/CONCIL
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ANULAR_CONCIL',1,getdate())
go

INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ANULAR_LOTE_PREST',1,getdate())
go

INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ANULAR_LOTE_FACT',1,getdate())
go

--Permisos de ANULAR LOTE
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ANULAR_LOTE_PREST',2,getdate())
go

--Permisos de ANULAR LOTE
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ANULAR_LOTE_PREST',3,getdate())
go