INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_TAR','Tarifas Periodos Productos',8);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_TAR_CNS','Consultar registros en Tarifas Periodos',NULL);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_TAR_DEL','Eliminar registros en Tarifas Periodos P',NULL);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_TAR_INS','Insertar registros en Tarifas Periodos P',NULL);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_TAR_UPD','Editar registros en Tarifas Periodos Pro',NULL);
