INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_PER','Periodos Productos',8);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_PER_CNS','Consultar registros en Periodos Producto',NULL);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_PER_DEL','Eliminar registros en Periodos Productos',NULL);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_PER_INS','Insertar registros en Periodos Productos',NULL);
INSERT INTO dbo.TCF017_ACCESOS (ID_ACCESO,D_ACCESO,ID_MENU) VALUES('ABMC_PRO_PER_UPD','Editar registros en Periodos Productos',NULL)