--ABMC
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_ADM',5, getdate());

--ABMC Productos
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_BAS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_BAS_CNS',5, getdate());
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_BAS_INS',1,'2014-01-22 11:39:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_BAS_UPD',1,'2014-01-22 11:39:00.0');

--Productos Precios
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_PRE',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_PRE_CNS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_PRE_INS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_PRE_UPD',5, getdate());

--Productos Sectores
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_SEC',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_SEC_CNS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_SEC_INS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRO_SEC_UPD',5, getdate());


--ABMC Proveedores
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_BAS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_BAS_CNS',5, getdate());
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_BAS_INS',1,'2014-01-22 11:39:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_BAS_UPD',1,'2014-01-22 11:39:00.0');
 

-- Proveedores Periodos
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_PER',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_PER_CNS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_PER_INS',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_PER_UPD',5, getdate());

--Proveedores Valores
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_VAL',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_VAL_CNS',5, getdate());
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_VAL_INS',1,'2014-01-22 11:39:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_PRV_VAL_UPD',1,'2014-01-22 11:39:00.0');

--ABMC Sectores
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_SEC',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_SEC_CNS',5, getdate());
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_SEC_INS',1,'2014-01-22 11:39:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_SEC_UPD',1,'2014-01-22 11:39:00.0');

--Busqueda de conciliaciones
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('BUSQUEDA_CONCIL',5,getdate());

INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_TAB',5, getdate());
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_TAB_CNS',5, getdate());
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_TAB_INS',1,'2014-01-22 10:33:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_TAB_UPD',1,'2014-01-22 10:33:00.0');

--ABMC Usuario
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ABMC_USU',5, getdate());
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('ALTA_USU',1,'2013-10-30 00:00:00.0');

INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('AMBC_PAR',1,getdate());

--Bienvenida
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('BIENVENIDA',5, getdate());
--Conciliaciones
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONC_SRV',5, getdatre());
--Menu Consultas
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONSULTAS',5,getdate());
--Consulta de Diferencias de Conciliaciones
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONSULTAS_DIF_CONCIL',5,getdate());

--Consulta Servicios Facturados
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONSULTAS_SERV_FACT',5,getdate());
--Consulta Servicios Prestados
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONS_SERV_PREST',5,getdate());
--Consulta Servicios Prestados Detalle
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONS_SERV_PREST_DET',5,getdate());
--Importar Servicios Facturados
INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('IMPORT_SERV_FACT',5,getdate());

--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('IMP_SERV_FACT',5,getdate());
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('IMP_SERV_PREST',1,'2014-02-24 10:26:00.0')
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('EDIT_DIF_CONCIL',1,'2014-03-27 11:09:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONS_ACT_LOTES',1,'2014-02-24 10:26:00.0');

--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONC_SRV_APR',1,'2014-02-06 16:00:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONC_SRV_DIF',1,'2014-02-06 16:00:00.0');
--INSERT INTO dbo.TCF018_ACCESOS_POR_PERFILES (ID_ACCESO,ID_PERFIL,F_ALTA) VALUES('CONC_SRV_GRA',1,'2014-02-06 16:00:00.0');