SET IDENTITY_INSERT dbo.TCF019_PERFILES ON
INSERT INTO dbo.TCF019_PERFILES (ID_PERFIL,D_PERFIL,N_NIVEL_MENSAJE,C_USUA_ALTA,F_ALTA,C_USUA_ACTUAC,F_ACTUAC) VALUES(7,'CONSGRAL',0,1,getDate(),NULL,NULL)
SET IDENTITY_INSERT dbo.TCF019_PERFILES OFF