INSERT INTO TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF)
    VALUES('TIPVAL','1','Valorizacion Normal','Val Normal',NULL,NULL,NULL,'S',getdate(),'admin',NULL,NULL)

INSERT INTO TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF)
    VALUES('TIPVAL','2','Rangos Cantidades','Rangos Cant',NULL,NULL,NULL,'S',getdate(),'admin',NULL,NULL)

INSERT INTO TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF)
    VALUES('TIPVAL','3','Rangos Importes y % Comisión','Rangos Imp-% Com',NULL,NULL,NULL,'S',getdate(),'admin',NULL,NULL)