INSERT INTO TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF)
    VALUES('MONEDA','PES','Pesos Argentinos','Pesos Arg',NULL,NULL,NULL,'S',getdate(),'admin',NULL,NULL)

INSERT INTO TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF)
    VALUES('MONEDA','U$D','Dolares BNA','Dólar BNA',NULL,NULL,NULL,'S',getdate(),'admin',NULL,NULL)

INSERT INTO TCF001_GENERAL (CD_TABLA,CD_CODTABLA,NB_CODTABLA,NB_CODTABLACORTO,NB_ATRIBUTOTABLA1,NB_ATRIBUTOTABLA2,NB_ATRIBUTOTABLA3,ST_HABILITADO,FH_ALTA,NB_USUARIOALTA,FH_MODIFICACION,NB_USUARIOMODIF)
    VALUES('MONEDA','EUR','Euros BNA','Euro BNA',NULL,NULL,NULL,'S',getdate(),'admin',NULL,NULL)